"""
LSH banding over the fixed k=600 MinHash sketch from Task B (minhash.py).
Reuses that sketch -- no extra space, no extra sketching pass.
"""


def candidate_probability(s: float, b: int, r: int) -> float:
    """Closed-form S-curve: P(>=1 band matches | true Jaccard s), for
    b bands of r rows each drawn from the same MinHash signature."""
    return 1 - (1 - s ** r) ** b


def band_keys(sig: list, b: int, r: int):
    """b band keys for one signature; two notices are candidates iff any
    one of their band keys is equal."""
    assert len(sig) == b * r
    for i in range(b):
        yield i, tuple(sig[i * r : (i + 1) * r])


def build_index(sketches: dict, b: int, r: int):
    """sketches: {notice_id: signature list}. Returns candidate pairs (as a
    set of frozensets) generated by band-bucket collisions."""
    buckets = {}
    for nid, sig in sketches.items():
        for band_idx, key in band_keys(sig, b, r):
            buckets.setdefault((band_idx, key), []).append(nid)

    candidates = set()
    for members in buckets.values():
        if len(members) < 2:
            continue
        for i in range(len(members)):
            for j in range(i + 1, len(members)):
                candidates.add(frozenset((members[i], members[j])))
    return candidates, buckets
